manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import: true

    - name: lvgl
      remote: zephyrproject-rtos
      revision: master
      path: modules/lib/lvgl

  self:
    path: Acrylix.git
