# this was set for the esp32 for some reason, I forget, something to do with memory jumps?
# CONFIG_COMPILER_OPT="-mlongcalls"
# Console output
CONFIG_UART_CONSOLE=y

# GPIO driver
CONFIG_GPIO=y

# Uncomment these as you need them:
# CONFIG_SPI=y
# CONFIG_I2C=y
# CONFIG_PWM=y
# CONFIG_ADC=y
